#!/bin/bash -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function usage {
	cat >&2 <<DONE
Usage: $0 [-b bind_address] [-p port]
Options
 -b BIND_ADDRESS     Address to bind to (default 0.0.0.0)
 -p PORT             Port to bind to (default 16342)
DONE
	exit 1
}

BIND_ADDR="127.0.0.1"
BIND_PORT="16342"
while getopts "b:p:h" opt; do
	case $opt in
		b)
			BIND_ADDR="$OPTARG"
			;;
		p)
			BIND_PORT="$OPTARG"
			;;
		h)
			usage
			;;
	esac
	shift $((OPTIND-1)); OPTIND=1
done

docker run -it --init --rm \
	--name tinymce-clean-server \
	-v "$DIR":/usr/src/app \
	-w /usr/src/app \
	-u node \
	-m "100M" --memory-swap "300M" \
	-e "TINYMCE_CLEAN_PORT=$BIND_PORT" \
	-p $BIND_ADDR:$BIND_PORT:$BIND_PORT \
	node:7-alpine \
	node server.js
